### ISSUE TITLE
Deserialization error for play.toClient : Read error for undefined : undefined is not a function

### ISSUE THREAD

**Issue by wujekbobixon** [PrismarineJS/mineflayer#2829]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: ^4.5.1
 - server: spigot 1.19.2
 - node: v14.15.0.

## Detailed description of a problem
Scripts worked on 1.18 but after update to 1.19.2 some functions doesnt work 
exactly bot.chat 
## What did you try yet?
removed node_modules 
updated all 
## Your current code
```js

TypeError: Deserialization error for play.toClient : Read error for undefined : undefined is not a function
    at eval (eval at compile (G:\BOTS\mc\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2475:52)
    at packet (eval at compile (G:\BOTS\mc\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2535:9)
    at CompiledProtodef.read (G:\BOTS\mc\node_modules\protodef\src\compiler.js:70:12)
    at e.message (G:\BOTS\mc\node_modules\protodef\src\compiler.js:111:49)
    at tryCatch (G:\BOTS\mc\node_modules\protodef\src\utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (G:\BOTS\mc\node_modules\protodef\src\compiler.js:111:29)
    at FullPacketParser.parsePacketBuffer (G:\BOTS\mc\node_modules\protodef\src\serializer.js:68:23)
    at FullPacketParser._transform (G:\BOTS\mc\node_modules\protodef\src\serializer.js:74:21)
    at FullPacketParser.Transform._read (G:\BOTS\mc\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:177:10)     
    at FullPacketParser.Transform._write (G:\BOTS\mc\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:164:83) {  
  field: 'play.toClient'
}
```

**Comment by extremeheat** [comment]
1.19.2 is not currently supported. #2797, consider contributing.
